[default]
fg = "#000000"
bg = "#ffffff"

[selection]
fg = "#ff0000"

[selection-highlight]
fg = "#004DFF"

[color-selection]
fg = "#000000"

[jump-grid]
fg = "#800080"

[cursor-drawing]
fg = "#00008b"

[cursor-block]
attributes = ["reverse"]

[tooltip]
fg = "#808080"
